// Code generated by xcolor/codegen/main.go. DO NOT EDIT.

package xcolor

func Black(format string, a ...any) {
	printfln(getByID(CodeFgBlack), format, a...)
}

func HiBlack(format string, a ...any) {
	printfln(getByID(CodeFgHiBlack), format, a...)
}

func BgBlack(format string, a ...any) {
	printfln(getByID(CodeBgBlack), format, a...)
}

func BgHiBlack(format string, a ...any) {
	printfln(getByID(CodeBgHiBlack), format, a...)
}

func BlackString(format string, a ...any) string {
	return getByID(CodeFgBlack).Sprintf(format, a...)
}

func HiBlackString(format string, a ...any) string {
	return getByID(CodeFgHiBlack).Sprintf(format, a...)
}

func BgBlackString(format string, a ...any) string {
	return getByID(CodeBgBlack).Sprintf(format, a...)
}

func BgHiBlackString(format string, a ...any) string {
	return getByID(CodeBgHiBlack).Sprintf(format, a...)
}

func Red(format string, a ...any) {
	printfln(getByID(CodeFgRed), format, a...)
}

func HiRed(format string, a ...any) {
	printfln(getByID(CodeFgHiRed), format, a...)
}

func BgRed(format string, a ...any) {
	printfln(getByID(CodeBgRed), format, a...)
}

func BgHiRed(format string, a ...any) {
	printfln(getByID(CodeBgHiRed), format, a...)
}

func RedString(format string, a ...any) string {
	return getByID(CodeFgRed).Sprintf(format, a...)
}

func HiRedString(format string, a ...any) string {
	return getByID(CodeFgHiRed).Sprintf(format, a...)
}

func BgRedString(format string, a ...any) string {
	return getByID(CodeBgRed).Sprintf(format, a...)
}

func BgHiRedString(format string, a ...any) string {
	return getByID(CodeBgHiRed).Sprintf(format, a...)
}

func Green(format string, a ...any) {
	printfln(getByID(CodeFgGreen), format, a...)
}

func HiGreen(format string, a ...any) {
	printfln(getByID(CodeFgHiGreen), format, a...)
}

func BgGreen(format string, a ...any) {
	printfln(getByID(CodeBgGreen), format, a...)
}

func BgHiGreen(format string, a ...any) {
	printfln(getByID(CodeBgHiGreen), format, a...)
}

func GreenString(format string, a ...any) string {
	return getByID(CodeFgGreen).Sprintf(format, a...)
}

func HiGreenString(format string, a ...any) string {
	return getByID(CodeFgHiGreen).Sprintf(format, a...)
}

func BgGreenString(format string, a ...any) string {
	return getByID(CodeBgGreen).Sprintf(format, a...)
}

func BgHiGreenString(format string, a ...any) string {
	return getByID(CodeBgHiGreen).Sprintf(format, a...)
}

func Yellow(format string, a ...any) {
	printfln(getByID(CodeFgYellow), format, a...)
}

func HiYellow(format string, a ...any) {
	printfln(getByID(CodeFgHiYellow), format, a...)
}

func BgYellow(format string, a ...any) {
	printfln(getByID(CodeBgYellow), format, a...)
}

func BgHiYellow(format string, a ...any) {
	printfln(getByID(CodeBgHiYellow), format, a...)
}

func YellowString(format string, a ...any) string {
	return getByID(CodeFgYellow).Sprintf(format, a...)
}

func HiYellowString(format string, a ...any) string {
	return getByID(CodeFgHiYellow).Sprintf(format, a...)
}

func BgYellowString(format string, a ...any) string {
	return getByID(CodeBgYellow).Sprintf(format, a...)
}

func BgHiYellowString(format string, a ...any) string {
	return getByID(CodeBgHiYellow).Sprintf(format, a...)
}

func Blue(format string, a ...any) {
	printfln(getByID(CodeFgBlue), format, a...)
}

func HiBlue(format string, a ...any) {
	printfln(getByID(CodeFgHiBlue), format, a...)
}

func BgBlue(format string, a ...any) {
	printfln(getByID(CodeBgBlue), format, a...)
}

func BgHiBlue(format string, a ...any) {
	printfln(getByID(CodeBgHiBlue), format, a...)
}

func BlueString(format string, a ...any) string {
	return getByID(CodeFgBlue).Sprintf(format, a...)
}

func HiBlueString(format string, a ...any) string {
	return getByID(CodeFgHiBlue).Sprintf(format, a...)
}

func BgBlueString(format string, a ...any) string {
	return getByID(CodeBgBlue).Sprintf(format, a...)
}

func BgHiBlueString(format string, a ...any) string {
	return getByID(CodeBgHiBlue).Sprintf(format, a...)
}

func Magenta(format string, a ...any) {
	printfln(getByID(CodeFgMagenta), format, a...)
}

func HiMagenta(format string, a ...any) {
	printfln(getByID(CodeFgHiMagenta), format, a...)
}

func BgMagenta(format string, a ...any) {
	printfln(getByID(CodeBgMagenta), format, a...)
}

func BgHiMagenta(format string, a ...any) {
	printfln(getByID(CodeBgHiMagenta), format, a...)
}

func MagentaString(format string, a ...any) string {
	return getByID(CodeFgMagenta).Sprintf(format, a...)
}

func HiMagentaString(format string, a ...any) string {
	return getByID(CodeFgHiMagenta).Sprintf(format, a...)
}

func BgMagentaString(format string, a ...any) string {
	return getByID(CodeBgMagenta).Sprintf(format, a...)
}

func BgHiMagentaString(format string, a ...any) string {
	return getByID(CodeBgHiMagenta).Sprintf(format, a...)
}

func Cyan(format string, a ...any) {
	printfln(getByID(CodeFgCyan), format, a...)
}

func HiCyan(format string, a ...any) {
	printfln(getByID(CodeFgHiCyan), format, a...)
}

func BgCyan(format string, a ...any) {
	printfln(getByID(CodeBgCyan), format, a...)
}

func BgHiCyan(format string, a ...any) {
	printfln(getByID(CodeBgHiCyan), format, a...)
}

func CyanString(format string, a ...any) string {
	return getByID(CodeFgCyan).Sprintf(format, a...)
}

func HiCyanString(format string, a ...any) string {
	return getByID(CodeFgHiCyan).Sprintf(format, a...)
}

func BgCyanString(format string, a ...any) string {
	return getByID(CodeBgCyan).Sprintf(format, a...)
}

func BgHiCyanString(format string, a ...any) string {
	return getByID(CodeBgHiCyan).Sprintf(format, a...)
}

func White(format string, a ...any) {
	printfln(getByID(CodeFgWhite), format, a...)
}

func HiWhite(format string, a ...any) {
	printfln(getByID(CodeFgHiWhite), format, a...)
}

func BgWhite(format string, a ...any) {
	printfln(getByID(CodeBgWhite), format, a...)
}

func BgHiWhite(format string, a ...any) {
	printfln(getByID(CodeBgHiWhite), format, a...)
}

func WhiteString(format string, a ...any) string {
	return getByID(CodeFgWhite).Sprintf(format, a...)
}

func HiWhiteString(format string, a ...any) string {
	return getByID(CodeFgHiWhite).Sprintf(format, a...)
}

func BgWhiteString(format string, a ...any) string {
	return getByID(CodeBgWhite).Sprintf(format, a...)
}

func BgHiWhiteString(format string, a ...any) string {
	return getByID(CodeBgHiWhite).Sprintf(format, a...)
}

